name: RotheKnust Sommer 2016
favicon: null
layout_spectrum: 0.75275
typography_spectrum: 0.8030428611673415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5dcb7'
    - '#240a27'
    - '#403354'
    - '#b5a493'
    - '#975b61'
  brandStrength: 0.25
  lightness: 0.9113514595665038
  saturation: 0.8111835063900799
  rhythmicContrast: 0.6906427319627255
purpose: []
