name: RotheKnust Sommer 2016
favicon: null
layout_spectrum: 0.60326
typography_spectrum: 0.8030428611673415
title: Stemninger fra vores sommer 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5dcb7'
    - '#240a27'
    - '#403354'
    - '#b5a493'
    - '#975b61'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
